### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by yq3w** [BKLronin/numpyHDR#1]
Hello, I want to implement HDR on cm4. I'm glad to see your program, but there was an error prompt while I was running. Please help me see what the possible reason is. The error is:
Traceback (most recent call last):
  File "/home/pi/numpyHDR-main/makehdr.py", line 15, in <module>
    stack = pcb.get_exposure_stack()
  File "/home/pi/numpyHDR-main/picamburst.py", line 39, in get_exposure_stack
    while confirmed != gain_start in range(gain_start -1.0, gain_start +1.0):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by BKLronin** [comment]
Hi! Cool to see this being of use eventually.

I added a safety measure to intercept this error. The concept is that it is checking that the exposure of the initial test picture is in a usable range so the under and over exposure pictures are usable.
